DROP TABLE if EXISTS Segment CASCADE;


DROP TABLE if EXISTS Salle CASCADE;


DROP TABLE if EXISTS Poste CASCADE;


DROP TABLE if EXISTS Logiciel CASCADE;


DROP TABLE if EXISTS installer CASCADE;


DROP TABLE if EXISTS Types CASCADE;